FROM almalinux:9
ADD https://raw.githubusercontent.com/ishahulahmed/Join-DevOps/main/Notes/10-Docker/Session-49/Session-49.txt?token=GHSAT0AAAAAACVCSJ5JQ2NNEG2A4WB4N3BAZU4D26Q /tmp/session-49.txt
CMD ["sleep", "60"]
